### ISSUE TITLE
Add AWS Lambda

### ISSUE THREAD

**Issue by alias1** [peterdemin/web-automation-2017#4]
* https://aws.amazon.com/lambda/details/

There are also MANY projects based around this, or similar concepts:
* https://serverless.com/

I believe to other big SaaS-type vendors have their own versions of this too.

**Comment by peterdemin** [comment]
Hey, I see have a broad knowledge in this topic. How about I add you as a collaborator to the repo?

**Comment by alias1** [comment]
Definitely have an interest, and it's an area I've looked into a lot for Huginn over the years, as well as other ideas/projects. Wouldn't be against being added, but realistically not sure how much time/energy I have to write much for it, more along contributing ideas/areas to look into.

What level of depth are you looking to write to? Just a general overview of whats out there, or something deeper?

**Comment by peterdemin** [comment]
Initially, I wanted to have a medium-sized article. But as I dig deeper into the topic, I see that one article isn't enough.
So, my current vision is an overview in the form of an article and a separate resource like https://opensource.guide/ with in-depth information and Discourse forum.

**Comment by peterdemin** [comment]
Here's your invitation: https://github.com/peterdemin/web-automation-2017/invitations

**Comment by alias1** [comment]
Sounds like a good approach. I'm definitely a fan of the overview article aspect as well. Help narrow down the research for others: what exists, why should I care, etc.

**Comment by peterdemin** [comment]
Right. Regarding serverless, it's more of computation platform, then web
automation tool. I think including it will distract the reader

**Comment by alias1** [comment]
I guess it depends what level of detail you're wanting to go to in the guide. If you want to stick to pretty GUI's, then definitely too low level. But like, for me, i've found i'm paying $20/mo to get the level of zapier I need to run the zaps I want, and it would be cheaper (and likely easier to implement) it in Lambda/similar.

**Comment by peterdemin** [comment]
I think I don't quite understand the case. Can you show an example, please?

**Comment by alias1** [comment]
Simple use case: when I like a picture on instagram, save it to my dropbox, and rename it to follow a certain pattern.

Zapier can do this by using instagram, dropbox, and javascript manipulation steps, which requires a premium plan. The same could be done using AWS lambda and some code.

For small/easy use cases, zapier or similar is probably easier. But as soon as you want to do something slightly outside of what they allow, the flexibility of a code based solution makes way more sense.

**Comment by peterdemin** [comment]
Node-RED is good for this, is free and doesn't require coding.
I think, that AWS Lambda can be used as a deployment platform for any kind of web automated solutions.
But if you don't use any framework/library, it's the same as wiring up services with bash scripts.
